CREATE TABLE IF NOT EXISTS products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
 price_cents BIGINT NOT NULL CHECK (price_cents BETWEEN 0 AND 1000000000),
 stock BIGINT NOT NULL CHECK (stock >= 0)
);
CREATE TABLE IF NOT EXISTS orders (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 idempotency_key TEXT NOT NULL UNIQUE,
 request_hash TEXT NOT NULL,
 customer TEXT NOT NULL,
 status TEXT NOT NULL CHECK (status IN ('reserved', 'cancelled')),
 total_cents BIGINT NOT NULL DEFAULT 0 CHECK (total_cents >= 0),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS order_items (
 order_id BIGINT NOT NULL REFERENCES orders(id),
 product_id BIGINT NOT NULL REFERENCES products(id),
 quantity BIGINT NOT NULL CHECK (quantity > 0),
 unit_price_cents BIGINT NOT NULL CHECK (unit_price_cents >= 0),
 PRIMARY KEY (order_id, product_id)
);
-- Covers a common back-office query; see docs/queries.sql for EXPLAIN.
CREATE INDEX IF NOT EXISTS orders_customer_created_idx ON orders(customer, created_at DESC);
